### PR TITLE
Basic CLI version

### PR DESCRIPTION
**Pull request by dinsfire64**
Needed something that didn't depend on any GUI libraries so I could run this under mono in an Linux environment.

Both my cabinet and desktop are running Arch, so the GUI was not useful to me. I needed something that I could script up for easy song additions as well.

Sadly this meant making an additional project and a quick and dirty code copy. A nice TODO on this would be some #defines that would prevent all of the WPF libraries from being compiled or possibly bringing out the logic for selecting the chart to pull from into Core.

Thanks for the work on making the generator. Makes my cabinet really shine!

### CODE REVIEW

**Comment by StefanoFiumara** [comment]
Hi, thank you for the pull request!

Apologies for not including something more CLI friendly to begin with, my dedicab runs Ubuntu but my desktop runs Windows. Hopefully it wasn't too difficult for you to dissect the UI layer away.

Is your cabinet a DDR or an ITG cabinet? I'm curious if this method works on upgraded DDR machines, but I have no way to test this.

**Comment by dinsfire64** [comment]
Hey,

My JCab is running Arch Linux, using a JPAC for IO and a custom lighting board that implements SextetStream.

So to use this, I can just install Mono on the cabinet and have it generate the light chart when I copy over the new pack. Lately I've  just been using Syncthing on my home server to keep the song directory synced up. Either way I can just call the run the CLI and get the light charts made.

**Comment by StefanoFiumara** [comment]
Good to know that the light charts work on cabinets that are using other lighting solutions outside of PIUIO, this means that this application can reach a wider audience which is also awesome to hear.

I am currently working on another WPF app to automate the processing of songs that get added to my cabinet as well, it uses this same algorithm for the light charts and it also implements a few other useful features like tournament management and adding/removing song packs through a GUI. It may not be useful to someone using your setup, but you can check it out here: https://github.com/StefanoFiumara/Dedicab-Manager

**Comment by dinsfire64** [comment]
Very cool project!

The only other thing I may want to do with Lights-Builder is often times stepchart makers will put multiple versions of the same stepchart in a directory. It may be useful for the program prioritize newer stepchart file formats (SSC for split timing for example) and rename older files (sm, dwi sma, etc).

If I'm not mistaken, this is the priority of SM5's loading algorithm. https://github.com/stepmania/stepmania/blob/7275b70c03f28c186d18c801b52747da4d358341/src/Steps.cpp#L110

Essentially the issue is that I have generated the light charts for SM5, loaded them to my cabinet, had the cache files generated, and the lights aren't there. Turns out SM5 chose a different stepchart file in the directory, so I have to delete/rename the file, reset the cache for that file, then reload the song in SM5.

I just love getting blinded by high BPM with no lighting charts in StepMania. lol

**Comment by StefanoFiumara** [comment]
I chose to go with .sm files because most files I download from the internet usually only include .sm files and no .ssc, I did run into the same issue with the lights builder on songs from certain packs and I was planning on simply having the script rename the .ssc file so that stepmania will ignore it.

Supporting .ssc is probably not too difficult though I have not looked at the new syntax very closely.

**Comment by dinsfire64** [comment]
Yeah SM is the dominate format for sure.

And at cursory glance the only things that seems to been added was the split timing variables in the header, but documentation for stepmania is few and far in between as I'm sure you know.

http://ec2.stepmania.com/wiki/The_.SSC_file_format

**Pull request merged**
